#!/bin/bash

# ----------------------------------------------
# Author: Seyon Krishnathasan
# Student ID: 24586524
# Script Name: analysis
# ---------------------------------------------- 

# Check for one argument
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <cleaned_file.tsv>"
  exit 1
fi

file="$1"

# Find most popular game mechanic from cleaned file by splits mechanics in to spearate lines remvove blank lines
echo "The most popular game mechanics is $( \
  cut -f13 "$file" | tail -n +2 | \
  tr ',.' '\n' | sed 's/^ *//' | sed '/^$/d' | \
  sort | uniq -c | sort -nr | head -n1 | \
  awk '{print substr($0, index($0,$2)) " found in " $1 " games"}' \
)"

# Find most popular game domain
echo "The most game domain is $( \
  cut -f14 "$file" | tail -n +2 | \
  tr ',.' '\n' | sed 's/^ *//' | sed '/^$/d' | \
  sort | uniq -c | sort -nr | head -n1 | \
  awk '{print substr($0, index($0,$2)) " found in " $1 " games"}' \
)"

# find correation between year published and rating 
awk -F"\t" '
  NR>1 && $3 != "" && $9 != "" {  # skip header row 
    x = $3; y = $9;
    sum_x += x; sum_y += y;
    sum_xy += x * y;
    sum_x2 += x * x;
    sum_y2 += y * y;
    n++
  }
  END { # calculate the pearson coefficient 
    X = n * sum_xy - sum_x * sum_y
    Y = sqrt((n * sum_x2 - (sum_x)^2) * (n * sum_y2 - (sum_y)^2))
    r = X / Y
    printf "The correlation between the year of publication and the average rating is %.3f\n", r
  }
' "$file"

# Find correlation between complexity and rating 
awk -F"\t" '
  NR>1 && $11 != "" && $9 != "" {
    x = $11; y = $9;
    sum_x += x; sum_y += y;
    sum_xy += x * y;
    sum_x2 += x * x;
    sum_y2 += y * y;
    n++
  } 
  END { # calculate correlation 
    X = n * sum_xy - sum_x * sum_y
    Y = sqrt((n * sum_x2 - (sum_x)^2) * (n * sum_y2 - (sum_y)^2))
    r = X / Y
    printf "The correlation between the complexity of a game and its average rating is %.3f\n", r
  }
' "$file"
