#!/bin/bash

# ----------------------------------------------
# Author: Seyon Krishnathasan
# Student ID: 24586524
# Date: 19 May 2025
# Script Name: empty_cells
# ---------------------------------------------- 

# Check for exact 2 arguments 
if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <filename> <delimiter>"
  exit 1
fi

# Assign input arguments 
filename="$1" # input file
delimiter="$2" # field delimeter

# Use  awk to count empty cells
awk -F"$delimiter" '
NR==1 {
  # process teh header line in the file
  for (i=1; i<=NF; i++) {
    gsub(/^\/?/, "", $i)         # Remove any character "/" from the column name
    gsub(/[^[:print:]]/, "", $i) # Remove non-printable characters
    colnames[i] = $i  # store cleaned columns
    empty[i] = 0
  }
  next # skip the next line
}
{
  for (i=1; i<=NF; i++) {
    gsub(/^ +| +$/, "", $i)  # Trim whitespace from each fields
    if ($i == "") {
      empty[i]++
    }
  }
}
END {
  for (i=1; i<=length(colnames); i++) {
    print colnames[i] ": " empty[i] # print column names 
  }
}
' "$filename" # Input file passed to awk 