#!/bin/bash

# ----------------------------------------------
# Author: Seyon Krishnathasan
# Student ID: 24586524
# Script Name: preprocess
# ---------------------------------------------- 

# Argument check whetehr one arguemt is passed
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <filename>"
  exit 1
fi

filename="$1"

# Find largest existing ID in the first column
max_id=$(awk -F";" 'NR > 1 && $1 ~ /^[0-9]+$/ && $1 > max { max = $1 } END { print max }' "$filename")

# Process the file
awk -v max_id="$max_id" -F";" '
BEGIN {
  OFS = "\t"
  id_counter = max_id + 1
}
NR == 1 {
  for (i = 1; i <= NF; i++) {
    gsub(/\r/, "", $i)     # Clean each header fields
    gsub(/[^[:print:]]/, "", $i)     # Remove non printable characters
  }
  print    # Print cleaned header
  next
}
{
  for (i = 1; i <= NF; i++) {
    gsub(/\r/, "", $i)   # clean every fileds
    gsub(/[^[:print:]]/, "", $i)   # Remove non printable characters
    gsub(",", ".", $i)   # Convert commas to  decimals
  }

  # fix missing ID
  if ($1 == "") {
    $1 = id_counter
    id_counter++
  }

  print
}
' "$filename"
